apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apmserver
spec:
  destination:
    name: ''
    namespace: elastic-ns
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.elastic.co'
    targetRevision: 8.5.1
    chart: apm-server 
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

