apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoapp
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: smallapp/chart/smallapp
    repoURL: 'https://github.com/andrei-gutierrez/demo_app'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

