name: Build Docker
env:
  version: 1.2.1
on: 
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'
      - name: Build npm
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Run setup
        run: |
          cd smallapp
          npm install
          npm install @cloudnative/health-connect
          npm install elastic-apm-node --save
          # npm install node-gyp
          # npm install appmetrics-prometheus
          npm ci
          npm run build --if-present
          npm test 

      - name: Docker login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: runcmd
        run: ls
      - name: Build Docker
        uses: docker/build-push-action@v4.0.0
        with:
          context: smallapp
          file: smallapp/Dockerfile-run
          push: true
          tags: audreiev/smallapp:${{ env.version }}
   
